apiVersion: v2
appVersion: 2.11.2
description: A Helm chart for multicluster-engine
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-211@sha256:83074ffdded6e5eecf578314512723f9e2a76f0738bd448d8d9a86b851cf55fc
type: application
version: 2.11.2
